### PR TITLE
updating package.json files to add needed stuff like JWT, added auth.js

### PR DESCRIPTION
**Pull request by jmabie94**

### CODE REVIEW

**Comment by jmabie94** [comment]
fixed the merge conflict, just needs a quick approval
-- still need to figure out a way to integrate ApolloServer stuff so that we can do GQL and Mongo dbs with Login Authorization

**Comment by jmabie94** [comment]
added notes and a couple things based on what Mark was saying

**Comment by jmabie94** [comment]
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
DO NOT MERGE - TESTING NEEDED FIRST
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by jmabie94** [comment]
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
DO NOT MERGE - STILL TESTING
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by ctophr** [comment]
DO NOT MERGE

**Comment by jmabie94** [comment]
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
STILL DON'T MERGE PLEASE - BROKEN
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Pull request closed without merging**
